version: '3'
services:
  lendsqr-app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./:/app
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: lET@Jdnd8@mmdm&&%
      MYSQL_DATABASE: lendsqr-db
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'UNNM@#NNWD9mds'
    ports:
      - 3306:3306
    expose:
      - 3306

