import './globals.css'
import type { Metadata } from 'next'
import { Darker_Grotesque } from 'next/font/google'

const d_grotesque = Darker_Grotesque({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={d_grotesque.className}>
        {children}
        <script src="../node_modules/preline/dist/preline.js"></script>
      </body>
    </html>
  )
}
